#CREATE SCHEMA `itcrowd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE `itcrowd`.`T_TOPICS` (
  `F_TOPIC_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_TOPIC_NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`F_TOPIC_ID`),
  UNIQUE INDEX `F_TOPIC_ID_UNIQUE` (`F_TOPIC_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `itcrowd`.`T_INQUIRIES` (
  `F_INQUIRY_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_DESCRIPTION` TEXT NULL,
  `F_CREATE_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `F_MODIFIED_WHEN` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `F_CUSTOMER_NAME` VARCHAR(150) NOT NULL,
  `F_TOPIC_ID` BIGINT(12) NOT NULL,
  PRIMARY KEY (`F_INQUIRY_ID`),
  UNIQUE INDEX `F_INQUIRY_ID_UNIQUE` (`F_INQUIRY_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `itcrowd`.`T_ATTRIBUTES_OF_INQUIRY` (
  `F_ID` BIGINT(12) NOT NULL AUTO_INCREMENT,
  `F_INQUIRY_ID` BIGINT(12) NOT NULL,
  `F_NAME` VARCHAR(120) NOT NULL,
  `F_VALUE` VARCHAR(220) NOT NULL,
  PRIMARY KEY (`F_ID`),
  UNIQUE INDEX `F_ID_UNIQUE` (`F_ID` ASC)
)DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;